/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import logica.LOGProductos;

/**
 *
 * @author yordi
 */
public class IfrmRegistrarProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmRegistrarProducto
     */
    public IfrmRegistrarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblUnidadMedida = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        cbxAlimento = new javax.swing.JCheckBox();
        cbxElectronico = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        dchFechaCaducidad = new com.toedter.calendar.JDateChooser();
        lblFechaCaducidad = new javax.swing.JLabel();
        lblGarantiaMeses = new javax.swing.JLabel();
        lblFabricante = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtUnidadMedida = new javax.swing.JTextField();
        spnGarantiaMeses = new javax.swing.JSpinner();
        txtFabricante = new javax.swing.JTextField();
        spnPrecio = new javax.swing.JSpinner();
        spnStock = new javax.swing.JSpinner();
        btnSalir = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        lblNombre.setText("Nombre");

        lblUnidadMedida.setText("Unidad Medida");

        lblPrecio.setText("Precio");

        lblStock.setText("Stock");

        cbxAlimento.setText("Alimento");
        cbxAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlimentoActionPerformed(evt);
            }
        });

        cbxElectronico.setText("Electronico");
        cbxElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxElectronicoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Producto");

        lblFechaCaducidad.setText("Fecha Caducidad");

        lblGarantiaMeses.setText("Garantia Meses");

        lblFabricante.setText("Fabricante");

        spnGarantiaMeses.setModel(new javax.swing.SpinnerNumberModel());

        spnPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.1f));

        spnStock.setModel(new javax.swing.SpinnerNumberModel());

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxAlimento)
                            .addComponent(lblNombre)
                            .addComponent(lblUnidadMedida)
                            .addComponent(lblPrecio)
                            .addComponent(lblStock))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGarantiaMeses)
                            .addComponent(cbxElectronico)
                            .addComponent(lblFabricante)
                            .addComponent(txtNombre)
                            .addComponent(txtUnidadMedida, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(spnPrecio)
                            .addComponent(spnStock)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFechaCaducidad)
                        .addGap(30, 30, 30)
                        .addComponent(dchFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnRegistrar)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnGarantiaMeses)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaCaducidad)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblUnidadMedida)
                                    .addComponent(txtUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrecio)
                                    .addComponent(spnPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStock)
                                    .addComponent(spnStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxAlimento)
                                    .addComponent(cbxElectronico))
                                .addGap(47, 47, 47)
                                .addComponent(dchFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblGarantiaMeses)
                                .addComponent(spnGarantiaMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFabricante)
                    .addComponent(txtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxElectronicoActionPerformed
        cambiarElectronico();
    }//GEN-LAST:event_cbxElectronicoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbxAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlimentoActionPerformed
        cambiarAlimento();
    }//GEN-LAST:event_cbxAlimentoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            obtenerTodoVariables();
        } catch (SQLException ex) {
            System.getLogger(IfrmRegistrarProducto.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void obtenerTodoVariables() throws SQLException{
        
        if(!cbxAlimento.isSelected() && !cbxElectronico.isSelected()){
            JOptionPane.showMessageDialog(this, "Seleccionar un tipo de producto", "Error de validacioon", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        nombre = txtNombre.getText();
        unidadMedida = txtUnidadMedida.getText();
        precio = (float) spnPrecio.getValue();
        stock = (int) spnStock.getValue();
        
        if(cbxAlimento.isSelected()){
            fechaCaducidad = dchFechaCaducidad.getDate();
            
            if(LOGProductos.registrarAlimento(fechaCaducidad, nombre, unidadMedida, precio, stock)) System.out.println("Registro Exitoso");
            else System.err.println("Fallo en el registro");
            
            ;
            
        } else if(cbxElectronico.isSelected()){
            garantiaMeses = (int) spnGarantiaMeses.getValue();
            fabricante = txtFabricante.getText();
            
            if(LOGProductos.registrarElectronico(garantiaMeses, fabricante, nombre, unidadMedida, precio, stock)) System.out.println("Registro Exitoso");
            else System.err.println("Fallo en el registro");
            
            return;
        }
        
        
    }
    
    private void vaciarTodo(){
        txtNombre.setText("");
        txtUnidadMedida.setText("");
        spnPrecio.setValue(0);
        spnStock.setValue(0);
        
        dchFechaCaducidad.setDate(new Date());
        
        spnGarantiaMeses.setValue(0);
        txtFabricante.setText("");
    }
    
    private void vaciarParteInferior(){
        dchFechaCaducidad.setDate(new Date());
        
        spnGarantiaMeses.setValue(0);
        txtFabricante.setText("");
    }
    
    private void cambiarAlimento(){
        cbxElectronico.setSelected(false);
        
        txtFabricante.setVisible(false);
        spnGarantiaMeses.setVisible(false);
        
        dchFechaCaducidad.setVisible(true);
    }
    
    private void cambiarElectronico(){
        cbxAlimento.setSelected(false);
        
        txtFabricante.setVisible(true);
        spnGarantiaMeses.setVisible(true);
        
        dchFechaCaducidad.setVisible(false);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbxAlimento;
    private javax.swing.JCheckBox cbxElectronico;
    private com.toedter.calendar.JDateChooser dchFechaCaducidad;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFabricante;
    private javax.swing.JLabel lblFechaCaducidad;
    private javax.swing.JLabel lblGarantiaMeses;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblUnidadMedida;
    private javax.swing.JSpinner spnGarantiaMeses;
    private javax.swing.JSpinner spnPrecio;
    private javax.swing.JSpinner spnStock;
    private javax.swing.JTextField txtFabricante;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUnidadMedida;
    // End of variables declaration//GEN-END:variables

    private String nombre;
    private String unidadMedida;
    private float precio;
    private int stock;
    
    private Date fechaCaducidad;
    
    private int garantiaMeses;
    private String fabricante;
}
